name: Committee Transaction Numbers

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 0 * * *' 

jobs:
  update-vote-totals:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests pyyaml

    - name: Query koios for recent transactions
      id: query_api
      run: |
        python .github/scripts/update_transactions.py

    - name: Commit and push changes
      run: |
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            git stash
            git pull --rebase origin main
            git stash pop
            git add .
            git commit -m "Update transactions"
            git push origin HEAD:main